/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

//@ts-nocheck
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/FinalInterior.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[269.2, 6.47, 78.94]}
        rotation={[0, -1.34, 0]}
        scale={[36.14, 36.14, 36.14]}
      >
        <group
          position={[0.69, 3.03, -1.92]}
          rotation={[-Math.PI, 0.96, -Math.PI]}
          scale={[1, 1.32, 1]}
        >
          <mesh
            geometry={nodes.Plane008_1.geometry}
            material={nodes.Plane008_1.material}
          />
          <mesh
            geometry={nodes.Plane008_2.geometry}
            material={nodes.Plane008_2.material}
          />
        </group>
        <mesh
          geometry={nodes.Railing_Handrail.geometry}
          material={nodes.Railing_Handrail.material}
          position={[0.63, 3.22, -1.84]}
          rotation={[-Math.PI, 0.96, -Math.PI]}
          scale={[1, 1.26, 1]}
        />
        <group
          position={[0.63, 2.34, -1.84]}
          rotation={[-Math.PI, 0.96, -Math.PI]}
          scale={[1, 1.29, 1]}
        >
          <mesh
            geometry={nodes.Plane033.geometry}
            material={nodes.Plane033.material}
          />
          <mesh
            geometry={nodes.Plane033_1.geometry}
            material={nodes.Plane033_1.material}
          />
        </group>
        <group rotation={[-Math.PI, 1, -Math.PI]} scale={[0.94, 1, 1]}>
          <mesh
            geometry={nodes.Cylinder082_1.geometry}
            material={nodes.Cylinder082_1.material}
          />
          <mesh
            geometry={nodes.Cylinder082_2.geometry}
            material={nodes.Cylinder082_2.material}
          />
        </group>
      </group>
      <group
        position={[358.41, 30.13, 153.96]}
        rotation={[0, 0.58, 0]}
        scale={[36.14, 36.14, 36.14]}
      >
        <group
          position={[0.69, 3.07, -1.92]}
          rotation={[-Math.PI, 0.96, -Math.PI]}
          scale={[1, 1.28, 1]}
        >
          <mesh
            geometry={nodes.Plane011_1.geometry}
            material={nodes.Plane011_1.material}
          />
          <mesh
            geometry={nodes.Plane011_2.geometry}
            material={nodes.Plane011_2.material}
          />
        </group>
        <mesh
          geometry={nodes.Railing_Handrail001.geometry}
          material={nodes.Railing_Handrail001.material}
          position={[0.63, 3.44, -1.84]}
          rotation={[-Math.PI, 0.96, -Math.PI]}
          scale={[1, 1.23, 1]}
        />
        <group
          position={[0.63, 2.21, -1.84]}
          rotation={[-Math.PI, 0.96, -Math.PI]}
          scale={[1, 1.47, 1]}
        >
          <mesh
            geometry={nodes.Plane009_1.geometry}
            material={nodes.Plane009_1.material}
          />
          <mesh
            geometry={nodes.Plane009_2.geometry}
            material={nodes.Plane009_2.material}
          />
        </group>
        <group
          position={[0, -0.59, 0]}
          rotation={[-Math.PI, 1, -Math.PI]}
          scale={[0.94, 1.02, 1]}
        >
          <mesh
            geometry={nodes.Cylinder083_1.geometry}
            material={nodes.Cylinder083_1.material}
          />
          <mesh
            geometry={nodes.Cylinder083_2.geometry}
            material={nodes.Cylinder083_2.material}
          />
        </group>
      </group>
      <group
        position={[-381.12, 6.19, 122.69]}
        rotation={[-Math.PI, 0.11, -Math.PI]}
        scale={29.5}
      >
        <group position={[0, 0, 1.72]}>
          <mesh
            geometry={nodes.Human.geometry}
            material={nodes.Human.material}
          />
          <mesh
            geometry={nodes.Human_1.geometry}
            material={nodes.Human_1.material}
          />
          <mesh
            geometry={nodes.Human_3.geometry}
            material={nodes.Human_3.material}
          />
        </group>
        <group position={[1.44, 0, 1.2]} rotation={[0, 0.85, 0]}>
          <mesh
            geometry={nodes.Human001.geometry}
            material={nodes.Human001.material}
          />
          <mesh
            geometry={nodes.Human001_1.geometry}
            material={nodes.Human001_1.material}
          />
          <mesh
            geometry={nodes.Human001_2.geometry}
            material={nodes.Human001_2.material}
          />
        </group>
        <group position={[-1.12, 0, 1.32]} rotation={[0, -0.77, 0]}>
          <mesh
            geometry={nodes.Human002.geometry}
            material={nodes.Human002.material}
          />
          <mesh
            geometry={nodes.Human002_1.geometry}
            material={nodes.Human002_1.material}
          />
          <mesh
            geometry={nodes.Human002_2.geometry}
            material={nodes.Human002_2.material}
          />
        </group>
      </group>
      <group
        position={[199.34, 9.92, -81.97]}
        rotation={[Math.PI, -1.54, Math.PI]}
        scale={10.56}
      >
        <group position={[0.08, -0.35, 3.24]} scale={[2.53, 2.53, 3.3]}>
          <mesh
            geometry={nodes.Untitled003.geometry}
            material={nodes.Untitled003.material}
          />
          <mesh
            geometry={nodes.Untitled003_1.geometry}
            material={nodes.Untitled003_1.material}
          />
          <mesh
            geometry={nodes.Untitled003_2.geometry}
            material={nodes.Untitled003_2.material}
          />
          <mesh
            geometry={nodes.Untitled003_3.geometry}
            material={nodes.Untitled003_3.material}
          />
          <mesh
            geometry={nodes.Untitled003_4.geometry}
            material={nodes.Untitled003_4.material}
          />
          <mesh
            geometry={nodes.Untitled003_5.geometry}
            material={nodes.Untitled003_5.material}
          />
          <mesh
            geometry={nodes.Untitled003_6.geometry}
            material={nodes.Untitled003_6.material}
          />
          <mesh
            geometry={nodes.Untitled003_7.geometry}
            material={nodes.Untitled003_7.material}
          />
          <mesh
            geometry={nodes.Untitled003_8.geometry}
            material={nodes.Untitled003_8.material}
          />
          <mesh
            geometry={nodes.Untitled003_9.geometry}
            material={nodes.Untitled003_9.material}
          />
          <mesh
            geometry={nodes.Untitled003_10.geometry}
            material={nodes.Untitled003_10.material}
          />
          <mesh
            geometry={nodes.Untitled003_11.geometry}
            material={nodes.Untitled003_11.material}
          />
        </group>
        <group
          position={[-7.42, -0.37, 17.98]}
          rotation={[Math.PI, -1.48, Math.PI]}
          scale={[2.53, 2.53, 3.3]}
        >
          <mesh
            geometry={nodes.Untitled001.geometry}
            material={nodes.Untitled001.material}
          />
          <mesh
            geometry={nodes.Untitled001_1.geometry}
            material={nodes.Untitled001_1.material}
          />
          <mesh
            geometry={nodes.Untitled001_2.geometry}
            material={nodes.Untitled001_2.material}
          />
          <mesh
            geometry={nodes.Untitled001_3.geometry}
            material={nodes.Untitled001_3.material}
          />
          <mesh
            geometry={nodes.Untitled001_4.geometry}
            material={nodes.Untitled001_4.material}
          />
          <mesh
            geometry={nodes.Untitled001_5.geometry}
            material={nodes.Untitled001_5.material}
          />
          <mesh
            geometry={nodes.Untitled001_6.geometry}
            material={nodes.Untitled001_6.material}
          />
          <mesh
            geometry={nodes.Untitled001_7.geometry}
            material={nodes.Untitled001_7.material}
          />
          <mesh
            geometry={nodes.Untitled001_8.geometry}
            material={nodes.Untitled001_8.material}
          />
          <mesh
            geometry={nodes.Untitled001_9.geometry}
            material={nodes.Untitled001_9.material}
          />
          <mesh
            geometry={nodes.Untitled001_10.geometry}
            material={nodes.Untitled001_10.material}
          />
          <mesh
            geometry={nodes.Untitled001_11.geometry}
            material={nodes.Untitled001_11.material}
          />
        </group>
        <group
          position={[14.13, -0.37, 2.87]}
          rotation={[-Math.PI, 0.19, -Math.PI]}
          scale={[2.53, 2.53, 3.3]}
        >
          <mesh
            geometry={nodes.Untitled002.geometry}
            material={nodes.Untitled002.material}
          />
          <mesh
            geometry={nodes.Untitled002_1.geometry}
            material={nodes.Untitled002_1.material}
          />
          <mesh
            geometry={nodes.Untitled002_2.geometry}
            material={nodes.Untitled002_2.material}
          />
          <mesh
            geometry={nodes.Untitled002_3.geometry}
            material={nodes.Untitled002_3.material}
          />
          <mesh
            geometry={nodes.Untitled002_4.geometry}
            material={nodes.Untitled002_4.material}
          />
          <mesh
            geometry={nodes.Untitled002_5.geometry}
            material={nodes.Untitled002_5.material}
          />
          <mesh
            geometry={nodes.Untitled002_6.geometry}
            material={nodes.Untitled002_6.material}
          />
          <mesh
            geometry={nodes.Untitled002_7.geometry}
            material={nodes.Untitled002_7.material}
          />
          <mesh
            geometry={nodes.Untitled002_8.geometry}
            material={nodes.Untitled002_8.material}
          />
          <mesh
            geometry={nodes.Untitled002_9.geometry}
            material={nodes.Untitled002_9.material}
          />
          <mesh
            geometry={nodes.Untitled002_10.geometry}
            material={nodes.Untitled002_10.material}
          />
          <mesh
            geometry={nodes.Untitled002_11.geometry}
            material={nodes.Untitled002_11.material}
          />
        </group>
        <group
          position={[27.16, -0.35, 12.53]}
          rotation={[0, -0.23, 0]}
          scale={[2.53, 2.53, 3.3]}
        >
          <mesh
            geometry={nodes.Untitled004.geometry}
            material={nodes.Untitled004.material}
          />
          <mesh
            geometry={nodes.Untitled004_1.geometry}
            material={nodes.Untitled004_1.material}
          />
          <mesh
            geometry={nodes.Untitled004_2.geometry}
            material={nodes.Untitled004_2.material}
          />
          <mesh
            geometry={nodes.Untitled004_3.geometry}
            material={nodes.Untitled004_3.material}
          />
          <mesh
            geometry={nodes.Untitled004_4.geometry}
            material={nodes.Untitled004_4.material}
          />
          <mesh
            geometry={nodes.Untitled004_5.geometry}
            material={nodes.Untitled004_5.material}
          />
          <mesh
            geometry={nodes.Untitled004_6.geometry}
            material={nodes.Untitled004_6.material}
          />
          <mesh
            geometry={nodes.Untitled004_7.geometry}
            material={nodes.Untitled004_7.material}
          />
          <mesh
            geometry={nodes.Untitled004_8.geometry}
            material={nodes.Untitled004_8.material}
          />
          <mesh
            geometry={nodes.Untitled004_9.geometry}
            material={nodes.Untitled004_9.material}
          />
          <mesh
            geometry={nodes.Untitled004_10.geometry}
            material={nodes.Untitled004_10.material}
          />
          <mesh
            geometry={nodes.Untitled004_11.geometry}
            material={nodes.Untitled004_11.material}
          />
        </group>
        <group
          position={[-11.38, -0.35, 68.2]}
          rotation={[0, -1.02, 0]}
          scale={[2.53, 2.53, 3.3]}
        >
          <mesh
            geometry={nodes.Untitled005.geometry}
            material={nodes.Untitled005.material}
          />
          <mesh
            geometry={nodes.Untitled005_1.geometry}
            material={nodes.Untitled005_1.material}
          />
          <mesh
            geometry={nodes.Untitled005_2.geometry}
            material={nodes.Untitled005_2.material}
          />
          <mesh
            geometry={nodes.Untitled005_3.geometry}
            material={nodes.Untitled005_3.material}
          />
          <mesh
            geometry={nodes.Untitled005_4.geometry}
            material={nodes.Untitled005_4.material}
          />
          <mesh
            geometry={nodes.Untitled005_5.geometry}
            material={nodes.Untitled005_5.material}
          />
          <mesh
            geometry={nodes.Untitled005_6.geometry}
            material={nodes.Untitled005_6.material}
          />
          <mesh
            geometry={nodes.Untitled005_7.geometry}
            material={nodes.Untitled005_7.material}
          />
          <mesh
            geometry={nodes.Untitled005_8.geometry}
            material={nodes.Untitled005_8.material}
          />
          <mesh
            geometry={nodes.Untitled005_9.geometry}
            material={nodes.Untitled005_9.material}
          />
          <mesh
            geometry={nodes.Untitled005_10.geometry}
            material={nodes.Untitled005_10.material}
          />
          <mesh
            geometry={nodes.Untitled005_11.geometry}
            material={nodes.Untitled005_11.material}
          />
        </group>
        <group
          position={[11.65, -0.35, 53.35]}
          rotation={[0, 1.33, 0]}
          scale={[2.53, 2.53, 3.3]}
        >
          <mesh
            geometry={nodes.Untitled006.geometry}
            material={nodes.Untitled006.material}
          />
          <mesh
            geometry={nodes.Untitled006_1.geometry}
            material={nodes.Untitled006_1.material}
          />
          <mesh
            geometry={nodes.Untitled006_2.geometry}
            material={nodes.Untitled006_2.material}
          />
          <mesh
            geometry={nodes.Untitled006_3.geometry}
            material={nodes.Untitled006_3.material}
          />
          <mesh
            geometry={nodes.Untitled006_4.geometry}
            material={nodes.Untitled006_4.material}
          />
          <mesh
            geometry={nodes.Untitled006_5.geometry}
            material={nodes.Untitled006_5.material}
          />
          <mesh
            geometry={nodes.Untitled006_6.geometry}
            material={nodes.Untitled006_6.material}
          />
          <mesh
            geometry={nodes.Untitled006_7.geometry}
            material={nodes.Untitled006_7.material}
          />
          <mesh
            geometry={nodes.Untitled006_8.geometry}
            material={nodes.Untitled006_8.material}
          />
          <mesh
            geometry={nodes.Untitled006_9.geometry}
            material={nodes.Untitled006_9.material}
          />
          <mesh
            geometry={nodes.Untitled006_10.geometry}
            material={nodes.Untitled006_10.material}
          />
          <mesh
            geometry={nodes.Untitled006_11.geometry}
            material={nodes.Untitled006_11.material}
          />
        </group>
        <group
          position={[2.76, -0.35, -34.21]}
          rotation={[Math.PI, -1.49, Math.PI]}
          scale={[2.53, 2.53, 3.3]}
        >
          <mesh
            geometry={nodes.Untitled007.geometry}
            material={nodes.Untitled007.material}
          />
          <mesh
            geometry={nodes.Untitled007_1.geometry}
            material={nodes.Untitled007_1.material}
          />
          <mesh
            geometry={nodes.Untitled007_2.geometry}
            material={nodes.Untitled007_2.material}
          />
          <mesh
            geometry={nodes.Untitled007_3.geometry}
            material={nodes.Untitled007_3.material}
          />
          <mesh
            geometry={nodes.Untitled007_4.geometry}
            material={nodes.Untitled007_4.material}
          />
          <mesh
            geometry={nodes.Untitled007_5.geometry}
            material={nodes.Untitled007_5.material}
          />
          <mesh
            geometry={nodes.Untitled007_6.geometry}
            material={nodes.Untitled007_6.material}
          />
          <mesh
            geometry={nodes.Untitled007_7.geometry}
            material={nodes.Untitled007_7.material}
          />
          <mesh
            geometry={nodes.Untitled007_8.geometry}
            material={nodes.Untitled007_8.material}
          />
          <mesh
            geometry={nodes.Untitled007_9.geometry}
            material={nodes.Untitled007_9.material}
          />
          <mesh
            geometry={nodes.Untitled007_10.geometry}
            material={nodes.Untitled007_10.material}
          />
          <mesh
            geometry={nodes.Untitled007_11.geometry}
            material={nodes.Untitled007_11.material}
          />
        </group>
        <group
          position={[-11.72, 4.77, 2.9]}
          rotation={[-Math.PI, 1.54, -Math.PI]}
          scale={[2.53, 2.53, 3.3]}
        >
          <mesh
            geometry={nodes.Untitled008.geometry}
            material={nodes.Untitled008.material}
          />
          <mesh
            geometry={nodes.Untitled008_1.geometry}
            material={nodes.Untitled008_1.material}
          />
          <mesh
            geometry={nodes.Untitled008_2.geometry}
            material={nodes.Untitled008_2.material}
          />
          <mesh
            geometry={nodes.Untitled008_3.geometry}
            material={nodes.Untitled008_3.material}
          />
          <mesh
            geometry={nodes.Untitled008_4.geometry}
            material={nodes.Untitled008_4.material}
          />
          <mesh
            geometry={nodes.Untitled008_5.geometry}
            material={nodes.Untitled008_5.material}
          />
          <mesh
            geometry={nodes.Untitled008_6.geometry}
            material={nodes.Untitled008_6.material}
          />
          <mesh
            geometry={nodes.Untitled008_7.geometry}
            material={nodes.Untitled008_7.material}
          />
          <mesh
            geometry={nodes.Untitled008_8.geometry}
            material={nodes.Untitled008_8.material}
          />
          <mesh
            geometry={nodes.Untitled008_9.geometry}
            material={nodes.Untitled008_9.material}
          />
          <mesh
            geometry={nodes.Untitled008_10.geometry}
            material={nodes.Untitled008_10.material}
          />
          <mesh
            geometry={nodes.Untitled008_11.geometry}
            material={nodes.Untitled008_11.material}
          />
        </group>
      </group>
      <group
        position={[123.24, 4.69, -90.39]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[32.15, 32.15, 23.03]}
      >
        <group
          position={[0, 0.08, 1.77]}
          rotation={[0, -0.5, 0]}
          scale={[0.87, 0.87, 1.52]}
        >
          <mesh
            geometry={nodes.Human004.geometry}
            material={nodes.Human004.material}
          />
          <mesh
            geometry={nodes.Human004_1.geometry}
            material={nodes.Human004_1.material}
          />
          <mesh
            geometry={nodes.Human004_2.geometry}
            material={nodes.Human004_2.material}
          />
        </group>
        <group
          position={[-2.53, 0.08, 6.68]}
          rotation={[0, -1.4, 0]}
          scale={[0.87, 0.87, 1.52]}
        >
          <mesh
            geometry={nodes.Human005.geometry}
            material={nodes.Human005.material}
          />
          <mesh
            geometry={nodes.Human005_1.geometry}
            material={nodes.Human005_1.material}
          />
          <mesh
            geometry={nodes.Human005_2.geometry}
            material={nodes.Human005_2.material}
          />
        </group>
        <group
          position={[6.25, 0.08, 4.17]}
          rotation={[0, -0.73, 0]}
          scale={[0.87, 0.87, 1.52]}
        >
          <mesh
            geometry={nodes.Human006.geometry}
            material={nodes.Human006.material}
          />
          <mesh
            geometry={nodes.Human006_1.geometry}
            material={nodes.Human006_1.material}
          />
          <mesh
            geometry={nodes.Human006_2.geometry}
            material={nodes.Human006_2.material}
          />
        </group>
        <group
          position={[6.31, 0.08, 11.67]}
          rotation={[-Math.PI, 0.66, -Math.PI]}
          scale={[0.87, 0.87, 1.52]}
        >
          <mesh
            geometry={nodes.Human003.geometry}
            material={nodes.Human003.material}
          />
          <mesh
            geometry={nodes.Human003_1.geometry}
            material={nodes.Human003_1.material}
          />
          <mesh
            geometry={nodes.Human003_2.geometry}
            material={nodes.Human003_2.material}
          />
        </group>
        <group
          position={[6.21, 0.06, -1.69]}
          rotation={[Math.PI, -0.32, Math.PI]}
          scale={[0.87, 0.87, 1.52]}
        >
          <mesh
            geometry={nodes.Human010.geometry}
            material={nodes.Human010.material}
          />
          <mesh
            geometry={nodes.Human010_1.geometry}
            material={nodes.Human010_1.material}
          />
          <mesh
            geometry={nodes.Human010_2.geometry}
            material={nodes.Human010_2.material}
          />
        </group>
        <group
          position={[-3.58, 0.35, 0.36]}
          rotation={[0, 1.48, 0]}
          scale={[1.02, 0.77, 1.47]}
        >
          <mesh
            geometry={nodes.Human011.geometry}
            material={nodes.Human011.material}
          />
          <mesh
            geometry={nodes.Human011_1.geometry}
            material={nodes.Human011_1.material}
          />
          <mesh
            geometry={nodes.Human011_2.geometry}
            material={nodes.Human011_2.material}
          />
        </group>
        <group
          position={[-3.62, 0.52, -5.07]}
          rotation={[0, 1.48, 0]}
          scale={[1.02, 0.77, 1.47]}
        >
          <mesh
            geometry={nodes.Human012.geometry}
            material={nodes.Human012.material}
          />
          <mesh
            geometry={nodes.Human012_1.geometry}
            material={nodes.Human012_1.material}
          />
          <mesh
            geometry={nodes.Human012_2.geometry}
            material={nodes.Human012_2.material}
          />
        </group>
      </group>
      <group position={[563.24, 5.61, -138.37]} scale={26.66}>
        <group position={[0, 0, 1.77]} scale={[1, 1.08, 1.25]}>
          <mesh
            geometry={nodes.Human007.geometry}
            material={nodes.Human007.material}
          />
          <mesh
            geometry={nodes.Human007_1.geometry}
            material={nodes.Human007_1.material}
          />
          <mesh
            geometry={nodes.Human007_2.geometry}
            material={nodes.Human007_2.material}
          />
        </group>
        <group
          position={[1.65, 0, 1.21]}
          rotation={[0, 0.64, 0]}
          scale={[1, 1.08, 1.25]}
        >
          <mesh
            geometry={nodes.Human008.geometry}
            material={nodes.Human008.material}
          />
          <mesh
            geometry={nodes.Human008_1.geometry}
            material={nodes.Human008_1.material}
          />
          <mesh
            geometry={nodes.Human008_2.geometry}
            material={nodes.Human008_2.material}
          />
        </group>
        <group
          position={[-1.25, 0, 1.25]}
          rotation={[0, -0.98, 0]}
          scale={[1, 1.08, 1.25]}
        >
          <mesh
            geometry={nodes.Human009.geometry}
            material={nodes.Human009.material}
          />
          <mesh
            geometry={nodes.Human009_1.geometry}
            material={nodes.Human009_1.material}
          />
          <mesh
            geometry={nodes.Human009_2.geometry}
            material={nodes.Human009_2.material}
          />
        </group>
      </group>
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={nodes.Cylinder006.material}
        position={[-794.36, -14.57, 9.23]}
        rotation={[0, 0, -1.55]}
        scale={[299.18, 1.76, 350.35]}
      />
      <mesh
        geometry={nodes.Cylinder024.geometry}
        material={nodes.Cylinder024.material}
        position={[142.89, 24.65, -48.15]}
        scale={[1.02, 13.45, 1.12]}
      />
      <mesh
        geometry={nodes.cube001.geometry}
        material={nodes.cube001.material}
        position={[159.99, 35.9, -80.58]}
        rotation={[1.55, 0, 0]}
        scale={[18.96, 0.42, 1.33]}
      />
      <mesh
        geometry={nodes.Cylinder025.geometry}
        material={nodes.Cylinder025.material}
        position={[130.16, 24.22, -122.4]}
        scale={[1.02, 13.78, 1.12]}
      />
      <mesh
        geometry={nodes.Cylinder026.geometry}
        material={nodes.Cylinder026.material}
        position={[111.01, 24.68, -48.46]}
        scale={[1.02, 13.48, 1.12]}
      />
      <mesh
        geometry={nodes.Cylinder028.geometry}
        material={nodes.Cylinder028.material}
        position={[87.83, 24.22, -122.4]}
        scale={[1.02, 13.78, 1.12]}
      />
      <mesh
        geometry={nodes.Cylinder029.geometry}
        material={nodes.Cylinder029.material}
        position={[12.34, 24.43, -48.15]}
        scale={[1.02, 13.39, 1.12]}
      />
      <mesh
        geometry={nodes.Cylinder033.geometry}
        material={nodes.Cylinder033.material}
        position={[13.57, 24.75, -94.06]}
        scale={[1.02, 13.79, 1.12]}
      />
      <mesh
        geometry={nodes.Cylinder034.geometry}
        material={nodes.Cylinder034.material}
        position={[-69.98, 24.2, -122.27]}
        scale={[1.02, 13.67, 1.12]}
      />
      <mesh
        geometry={nodes.Cylinder030.geometry}
        material={nodes.Cylinder030.material}
        position={[87.82, 24.91, -145.11]}
        scale={[1.02, 14.47, 1.12]}
      />
      <mesh
        geometry={nodes.Cylinder031.geometry}
        material={nodes.Cylinder031.material}
        position={[87.82, 24.19, -171.02]}
        scale={[1.02, 13.04, 1.12]}
      />
      <mesh
        geometry={nodes.Cylinder032.geometry}
        material={nodes.Cylinder032.material}
        position={[-68.89, 24.2, -163.67]}
        scale={[1.02, 13.67, 1.12]}
      />
      <mesh
        geometry={nodes.Cylinder036.geometry}
        material={nodes.Cylinder036.material}
        position={[175.75, 24.65, -48.15]}
        scale={[1.02, 13.45, 1.12]}
      />
      <mesh
        geometry={nodes.Cylinder037.geometry}
        material={nodes.Cylinder037.material}
        position={[177.5, 24.22, -122.4]}
        scale={[1.02, 13.78, 1.12]}
      />
      <mesh
        geometry={nodes.Cylinder038.geometry}
        material={nodes.Cylinder038.material}
        position={[206.39, 24.65, -48.15]}
        scale={[1.02, 13.45, 1.12]}
      />
      <mesh
        geometry={nodes.Cylinder039.geometry}
        material={nodes.Cylinder039.material}
        position={[212.35, 24.22, -122.4]}
        scale={[1.02, 13.78, 1.12]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials['Material.055']}
        position={[217.21, 35.9, -122.63]}
        rotation={[1.55, 0, 0]}
        scale={[18.96, 0.42, 1.33]}
      />
      <mesh
        geometry={nodes.Cylinder023.geometry}
        material={nodes.Cylinder023.material}
        position={[780.96, -15.42, 6.38]}
        rotation={[0, 0, -1.56]}
        scale={[295.72, 1.75, 379.96]}
      />
      <group
        position={[601.28, 110.82, -3.61]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[20.6, 240.12, 16.18]}
      >
        <mesh
          geometry={nodes.Cylinder047_1.geometry}
          material={nodes.Cylinder047_1.material}
        />
        <mesh
          geometry={nodes.Cylinder047_2.geometry}
          material={nodes.Cylinder047_2.material}
        />
      </group>
      <group
        position={[173.01, 135.74, -208.97]}
        rotation={[Math.PI, 0.02, -3.13]}
        scale={[25.17, 133.18, 22.17]}
      >
        <mesh
          geometry={nodes.Cylinder048_1.geometry}
          material={nodes.Cylinder048_1.material}
        />
        <mesh
          geometry={nodes.Cylinder048_2.geometry}
          material={nodes.Cylinder048_2.material}
        />
      </group>
      <group
        position={[171.77, 94.12, -200.84]}
        rotation={[Math.PI, 0.02, -3.13]}
        scale={[7.2, 10.53, 4.59]}
      >
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={nodes.Cube002_1.material}
        />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={nodes.Cube002_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials['Material.005']}
        position={[113.54, 6.79, -121.8]}
        scale={[1066.23, 61.8, 867.71]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[87.82, 24.6, -208.35]}
        scale={[1.02, 14.01, 1.12]}
      />
      <mesh
        geometry={nodes.Cylinder046.geometry}
        material={nodes.Cylinder046.material}
        position={[-73.2, 7.67, 121.8]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder048.geometry}
        material={nodes.Cylinder048.material}
        position={[-92.13, 7.67, 121.8]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder049.geometry}
        material={nodes.Cylinder049.material}
        position={[-83.92, 7.67, 130.93]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder050.geometry}
        material={nodes.Cylinder050.material}
        position={[-83.92, 7.67, 110.89]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder051.geometry}
        material={nodes.Cylinder051.material}
        position={[-28.83, 7.67, 131.12]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder052.geometry}
        material={nodes.Cylinder052.material}
        position={[-28.83, 7.67, 110.89]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder053.geometry}
        material={nodes.Cylinder053.material}
        position={[-38.42, 7.67, 121.33]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder054.geometry}
        material={nodes.Cylinder054.material}
        position={[-18.03, 7.67, 121.33]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder055.geometry}
        material={materials['Material.016']}
        position={[-6.6, 7.67, 178.71]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder056.geometry}
        material={materials['Material.014']}
        position={[-6.6, 7.67, 159.3]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder057.geometry}
        material={nodes.Cylinder057.material}
        position={[10.45, 7.67, 159.3]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder058.geometry}
        material={materials['Material.012']}
        position={[-25.56, 7.67, 213.92]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder059.geometry}
        material={materials['Material.013']}
        position={[-40.87, 7.67, 213.92]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder060.geometry}
        material={materials['Material.017']}
        position={[-24.92, 7.67, 201.73]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder061.geometry}
        material={materials['Material.018']}
        position={[-41.81, 7.67, 201.73]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder062.geometry}
        material={materials['Material.046']}
        position={[-33.11, 14.45, 207.67]}
        scale={[13.23, 6.04, 12.73]}
      />
      <mesh
        geometry={nodes.Cylinder063.geometry}
        material={materials['Material.019']}
        position={[-78.54, 7.67, 226.26]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder064.geometry}
        material={materials['Material.020']}
        position={[-93.85, 7.67, 226.26]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder065.geometry}
        material={materials['Material.021']}
        position={[-77.9, 7.67, 214.07]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder066.geometry}
        material={materials['Material.022']}
        position={[-94.79, 7.67, 214.07]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder067.geometry}
        material={materials['Material.023']}
        position={[-111.71, 7.67, 184.2]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder068.geometry}
        material={materials['Material.024']}
        position={[-127.02, 7.67, 184.2]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder069.geometry}
        material={materials['Material.025']}
        position={[-111.07, 7.67, 172.01]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder070.geometry}
        material={materials['Material.026']}
        position={[-127.96, 7.67, 172.01]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder071.geometry}
        material={materials['Material.027']}
        position={[-82.89, 14.45, 120.95]}
        scale={[13.23, 6.04, 12.73]}
      />
      <mesh
        geometry={nodes.Cylinder072.geometry}
        material={materials['Material.028']}
        position={[-27.94, 14.45, 120.95]}
        scale={[13.23, 6.04, 12.73]}
      />
      <mesh
        geometry={nodes.Cylinder073.geometry}
        material={materials['Material.047']}
        position={[-119.26, 14.32, 177.87]}
        scale={[13.23, 6.04, 12.73]}
      />
      <mesh
        geometry={nodes.Cylinder074.geometry}
        material={materials['Material.029']}
        position={[-86.09, 14.45, 220.01]}
        scale={[13.23, 6.04, 12.73]}
      />
      <mesh
        geometry={nodes.Cylinder075.geometry}
        material={materials['Material.030']}
        position={[-83.1, 7.98, 172.01]}
        scale={[2.15, 2.36, 2.34]}
      />
      <mesh
        geometry={nodes.Cylinder076.geometry}
        material={materials['Material.031']}
        position={[-45.26, 7.98, 172.01]}
        scale={[2.15, 2.36, 2.34]}
      />
      <mesh
        geometry={nodes.Cylinder077.geometry}
        material={materials['Material.032']}
        position={[-64.14, 7.98, 150.04]}
        scale={[2.15, 2.36, 2.34]}
      />
      <mesh
        geometry={nodes.Cylinder078.geometry}
        material={materials['Material.033']}
        position={[-64.14, 7.98, 187.23]}
        scale={[2.15, 2.36, 2.34]}
      />
      <mesh
        geometry={nodes.Cylinder079.geometry}
        material={materials['Material.034']}
        position={[10.45, 7.67, 176.87]}
        scale={[2.15, 2.04, 1.84]}
      />
      <mesh
        geometry={nodes.Cylinder080.geometry}
        material={materials['Material.035']}
        position={[2.02, 14.45, 169.28]}
        scale={[15.29, 6.04, 16.25]}
      />
      <mesh
        geometry={nodes.Cylinder081.geometry}
        material={materials['Material.036']}
        position={[-64.14, 18.13, 169.28]}
        scale={[23.93, 8.41, 22.88]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials['Material.037']}
        position={[192.12, 27.79, 149.93]}
        rotation={[-Math.PI, 0.1, -Math.PI]}
        scale={[1.02, 18.96, 9.05]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials['Material.038']}
        position={[200.8, 27.04, 35.7]}
        rotation={[-Math.PI, 0.14, -Math.PI]}
        scale={[1, 18.55, 8.85]}
      />
      <group
        position={[-220.28, 44.68, 166.27]}
        rotation={[0, -1.28, -1.76]}
        scale={[7.1, 5.4, 7.46]}
      >
        <mesh
          geometry={nodes.Plane004_1.geometry}
          material={nodes.Plane004_1.material}
        />
        <mesh
          geometry={nodes.Plane004_2.geometry}
          material={nodes.Plane004_2.material}
        />
      </group>
      <group
        position={[-215.91, 23.97, 180.3]}
        rotation={[0, -1.28, 0.07]}
        scale={[13.5, 12.17, 20.88]}
      >
        <mesh
          geometry={nodes.Cube012_1.geometry}
          material={nodes.Cube012_1.material}
        />
        <mesh
          geometry={nodes.Cube012_2.geometry}
          material={nodes.Cube012_2.material}
        />
        <mesh
          geometry={nodes.Cube012_3.geometry}
          material={nodes.Cube012_3.material}
        />
      </group>
      <group
        position={[-257.21, 44.68, 171.15]}
        rotation={[-Math.PI, -1.49, 1.39]}
        scale={[7.1, 5.4, 7.46]}
      >
        <mesh
          geometry={nodes.Plane005_1.geometry}
          material={nodes.Plane005_1.material}
        />
        <mesh
          geometry={nodes.Plane005_2.geometry}
          material={nodes.Plane005_2.material}
        />
      </group>
      <group
        position={[-258.19, 23.97, 185.81]}
        rotation={[-Math.PI, -1.49, -3.07]}
        scale={[13.5, 12.17, 20.88]}
      >
        <mesh
          geometry={nodes.Cube013_1.geometry}
          material={nodes.Cube013_1.material}
        />
        <mesh
          geometry={nodes.Cube013_2.geometry}
          material={nodes.Cube013_2.material}
        />
        <mesh
          geometry={nodes.Cube013_3.geometry}
          material={nodes.Cube013_3.material}
        />
      </group>
      <group
        position={[-296.53, 44.68, 161.31]}
        rotation={[Math.PI, -1.24, 1.39]}
        scale={[7.1, 5.4, 7.46]}
      >
        <mesh
          geometry={nodes.Plane006_1.geometry}
          material={nodes.Plane006_1.material}
        />
        <mesh
          geometry={nodes.Plane006_2.geometry}
          material={nodes.Plane006_2.material}
        />
      </group>
      <group
        position={[-302.11, 23.97, 179.25]}
        rotation={[Math.PI, -1.24, -3.07]}
        scale={[13.5, 12.17, 20.88]}
      >
        <mesh
          geometry={nodes.Cube014_1.geometry}
          material={nodes.Cube014_1.material}
        />
        <mesh
          geometry={nodes.Cube014_2.geometry}
          material={nodes.Cube014_2.material}
        />
        <mesh
          geometry={nodes.Cube014_3.geometry}
          material={nodes.Cube014_3.material}
        />
      </group>
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials['Material.042']}
        position={[-185.56, 25.94, 159.68]}
        rotation={[0, -1.53, 0]}
        scale={[3.13, 16.63, 10.93]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={nodes.Cube016.material}
        position={[424.01, 6.46, 156.51]}
        rotation={[Math.PI, -1.41, Math.PI]}
        scale={[23.85, 29.27, 18.57]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={nodes.Cube017.material}
        position={[431.17, 6.58, 110.14]}
        rotation={[Math.PI, -1.41, Math.PI]}
        scale={[23.85, 29.27, 18.57]}
      />
      <group
        position={[-528.71, 116.92, 15.16]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[20.6, 251.46, 16.18]}
      >
        <mesh
          geometry={nodes.Cylinder084_1.geometry}
          material={nodes.Cylinder084_1.material}
        />
        <mesh
          geometry={nodes.Cylinder084_2.geometry}
          material={nodes.Cylinder084_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[58.96, 25, -48.15]}
        scale={[1.02, 14.05, 1.12]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[-15.68, 6.06, -288.73]}
        rotation={[1.85, 0, 0]}
        scale={[44.32, 44.86, 42.47]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials['Material.048']}
        position={[166.44, 16.29, 154.73]}
        rotation={[-Math.PI, 0.82, 0]}
        scale={[-1, -4.77, -10.51]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials['Material.049']}
        position={[166.5, 26.37, 154.68]}
        rotation={[0, -0.82, 0]}
        scale={[0.93, 18.35, 8.35]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.070']}
        position={[-24.17, 7.15, 0.24]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[-233.36, -626.52, -289.93]}
      />
      <group
        position={[239.43, 135.74, -208.97]}
        rotation={[Math.PI, 0.02, -3.13]}
        scale={[25.17, 133.18, 22.17]}
      >
        <mesh
          geometry={nodes.Cylinder016.geometry}
          material={nodes.Cylinder016.material}
        />
        <mesh
          geometry={nodes.Cylinder016_1.geometry}
          material={nodes.Cylinder016_1.material}
        />
      </group>
      <group
        position={[238.2, 54.82, -200.84]}
        rotation={[Math.PI, 0.02, -3.13]}
        scale={[7.2, 10.53, 4.59]}
      >
        <mesh
          geometry={nodes.Cube020_1.geometry}
          material={nodes.Cube020_1.material}
        />
        <mesh
          geometry={nodes.Cube020_2.geometry}
          material={nodes.Cube020_2.material}
        />
      </group>
      <group
        position={[117.04, 135.74, -208.97]}
        rotation={[Math.PI, 0.02, -3.13]}
        scale={[25.17, 133.18, 22.17]}
      >
        <mesh
          geometry={nodes.Cylinder086_1.geometry}
          material={nodes.Cylinder086_1.material}
        />
        <mesh
          geometry={nodes.Cylinder086_2.geometry}
          material={nodes.Cylinder086_2.material}
        />
      </group>
      <group
        position={[115.81, 48.88, -200.84]}
        rotation={[Math.PI, 0.02, -3.13]}
        scale={[7.2, 10.53, 4.59]}
      >
        <mesh
          geometry={nodes.Cube021_1.geometry}
          material={nodes.Cube021_1.material}
        />
        <mesh
          geometry={nodes.Cube021_2.geometry}
          material={nodes.Cube021_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Plane009.geometry}
        material={nodes.Plane009.material}
        position={[601.77, 135.35, -234.07]}
        rotation={[2.42, 0, 0]}
        scale={[31.06, 45.58, 34.31]}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={nodes.Plane008.material}
        position={[601.77, 135.35, 242.9]}
        rotation={[0.73, 0, 0]}
        scale={[31.06, 45.58, 34.31]}
      />
      <mesh
        geometry={nodes.Plane010.geometry}
        material={materials['Material.053']}
        position={[-429.68, 27.25, 186.05]}
        rotation={[Math.PI / 2, 0, -1.47]}
        scale={[18.5, 20.52, 20.69]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.051']}
        position={[-329.59, 27.29, 176.97]}
        rotation={[Math.PI / 2, 0, -1.47]}
        scale={[18.5, 20.52, 20.69]}
      />
      <mesh
        geometry={nodes.Cylinder043.geometry}
        material={materials['Material.054']}
        position={[-441.7, 31.79, 131.71]}
        rotation={[-Math.PI, 1.29, -Math.PI]}
        scale={[29.38, 9.91, 18.73]}
      />
      <mesh
        geometry={nodes.Cylinder044.geometry}
        material={materials['Material.009']}
        position={[-326.66, 29.54, 128.95]}
        rotation={[0, 1.47, 0]}
        scale={[29.09, 9.91, 18.86]}
      />
      <mesh
        geometry={nodes.Cylinder047.geometry}
        material={materials['Material.001']}
        position={[-386.11, 43.64, 115.72]}
        rotation={[0, 1.47, 0]}
        scale={[44.01, 2.76, 49.1]}
      />
      <mesh
        geometry={nodes.Cylinder083.geometry}
        material={materials['Material.010']}
        position={[-386.11, 23.01, 115.72]}
        rotation={[0, 1.47, 0]}
        scale={[44.01, 10.8, 49.1]}
      />
      <mesh
        geometry={nodes.Cube020.geometry}
        material={materials['Material.006']}
        position={[-330.3, 30.78, 76.73]}
        rotation={[0, 0.68, 0]}
        scale={[7.17, 10.99, 19.41]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={materials['Material.050']}
        position={[-432.3, 29.41, 66.66]}
        rotation={[-Math.PI, 0.88, -Math.PI]}
        scale={[7.54, 10.99, 21.01]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={materials['Material.052']}
        position={[-381.08, 30.6, 178.25]}
        rotation={[-Math.PI, 1.53, -Math.PI]}
        scale={[1.96, 16, 51.87]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={materials['Material.045']}
        position={[-375.74, 30.18, 53.3]}
        rotation={[0, 1.47, 0]}
        scale={[6.93, 10.99, 19.96]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials['Material.060']}
        position={[611.55, 27.25, -202.91]}
        rotation={[Math.PI / 2, 0, 1.61]}
        scale={[18.5, 20.52, 20.69]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials['Material.064']}
        position={[512.16, 27.29, -188.03]}
        rotation={[Math.PI / 2, 0, 1.61]}
        scale={[18.5, 20.52, 20.69]}
      />
      <mesh
        geometry={nodes.Cylinder084.geometry}
        material={materials['Material.063']}
        position={[626.71, 31.79, -149.36]}
        rotation={[0, -1.23, 0]}
        scale={[29.38, 9.91, 18.73]}
      />
      <mesh
        geometry={nodes.Cylinder085.geometry}
        material={materials['Material.056']}
        position={[512.03, 29.54, -139.91]}
        rotation={[Math.PI, -1.53, Math.PI]}
        scale={[29.09, 9.91, 18.86]}
      />
      <mesh
        geometry={nodes.Cylinder086.geometry}
        material={materials['Material.059']}
        position={[572.15, 43.64, -130.17]}
        rotation={[Math.PI, -1.53, Math.PI]}
        scale={[44.01, 2.76, 49.1]}
      />
      <mesh
        geometry={nodes.Cylinder087.geometry}
        material={materials['Material.057']}
        position={[572.15, 23.01, -130.17]}
        rotation={[Math.PI, -1.53, Math.PI]}
        scale={[44.01, 10.8, 49.1]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={materials['Material.062']}
        position={[518.7, 30.78, -88]}
        rotation={[Math.PI, -0.74, Math.PI]}
        scale={[7.17, 10.99, 19.41]}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={materials['Material.058']}
        position={[621.11, 29.41, -83.88]}
        rotation={[0, -0.82, 0]}
        scale={[7.54, 10.99, 21.01]}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={materials['Material.065']}
        position={[563.48, 30.6, -192.3]}
        rotation={[0, -1.47, 0]}
        scale={[1.96, 16, 51.87]}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={materials['Material.061']}
        position={[565.43, 30.18, -67.25]}
        rotation={[Math.PI, -1.53, Math.PI]}
        scale={[6.93, 10.99, 19.96]}
      />
      <mesh
        geometry={nodes.Cube028.geometry}
        material={nodes.Cube028.material}
        position={[217.86, 22.5, 51.17]}
        rotation={[0, 1.42, 0]}
        scale={[2.65, 16.11, 16.06]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials['Material.067']}
        position={[217.86, 22.5, 80.51]}
        rotation={[0, 1.42, 0]}
        scale={[2.65, 16.11, 16.06]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials['Material.068']}
        position={[217.86, 22.5, 106.69]}
        rotation={[0, 1.42, 0]}
        scale={[2.65, 16.11, 16.06]}
      />
      <mesh
        geometry={nodes.Cube029.geometry}
        material={materials['Material.069']}
        position={[217.86, 22.5, 145.43]}
        rotation={[0, 1.42, 0]}
        scale={[2.65, 16.11, 16.06]}
      />
      <mesh
        geometry={nodes.cube.geometry}
        material={nodes.cube.material}
        position={[-61.85, 22.5, -235.09]}
        rotation={[0, -0.01, 0]}
        scale={[2.65, 16.11, 16.06]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[-34.7, 22.5, -235.09]}
        rotation={[0, -0.01, 0]}
        scale={[2.65, 16.11, 16.06]}
      />
      <mesh
        geometry={nodes.Cube030.geometry}
        material={nodes.Cube030.material}
        position={[-6.16, 22.5, -235.09]}
        rotation={[0, -0.01, 0]}
        scale={[2.65, 16.11, 16.06]}
      />
      <mesh
        geometry={nodes.Cube031.geometry}
        material={nodes.Cube031.material}
        position={[27.02, 22.5, -235.09]}
        rotation={[0, -0.01, 0]}
        scale={[2.65, 16.11, 16.06]}
      />
      <mesh
        geometry={nodes.Plane011.geometry}
        material={nodes.Plane011.material}
        position={[-526.51, 6.06, -288.65]}
        rotation={[1.81, 0, 0]}
        scale={[37, 44.86, 42.47]}
      />
      <mesh
        geometry={nodes.Plane012.geometry}
        material={nodes.Plane012.material}
        position={[-530.63, 144.33, -226.82]}
        rotation={[2.45, 0, -0.01]}
        scale={[30.79, 44.85, 42.46]}
      />
      <mesh
        geometry={nodes.Plane013.geometry}
        material={nodes.Plane013.material}
        position={[-529.68, 150.42, 224.83]}
        rotation={[0.62, 0, -0.01]}
        scale={[30.79, 44.85, 42.46]}
      />
      <group
        position={[408.5, 44.68, -159.88]}
        rotation={[Math.PI, 1.09, 1.39]}
        scale={[7.1, 5.4, 7.46]}
      >
        <mesh
          geometry={nodes.Plane020.geometry}
          material={nodes.Plane020.material}
        />
        <mesh
          geometry={nodes.Plane020_1.geometry}
          material={nodes.Plane020_1.material}
        />
      </group>
      <group
        position={[401.56, 23.97, -172.83]}
        rotation={[-Math.PI, 1.09, -3.07]}
        scale={[13.5, 12.17, 20.88]}
      >
        <mesh
          geometry={nodes.Cube005_1.geometry}
          material={nodes.Cube005_1.material}
        />
        <mesh
          geometry={nodes.Cube005_2.geometry}
          material={nodes.Cube005_2.material}
        />
        <mesh
          geometry={nodes.Cube005_3.geometry}
          material={nodes.Cube005_3.material}
        />
      </group>
      <group
        position={[443.85, 44.68, -171.64]}
        rotation={[Math.PI, 1.46, 1.39]}
        scale={[7.1, 5.4, 7.46]}
      >
        <mesh
          geometry={nodes.Plane021.geometry}
          material={nodes.Plane021.material}
        />
        <mesh
          geometry={nodes.Plane021_1.geometry}
          material={nodes.Plane021_1.material}
        />
      </group>
      <group
        position={[442.04, 23.97, -186.23]}
        rotation={[-Math.PI, 1.46, -3.07]}
        scale={[13.5, 12.17, 20.88]}
      >
        <mesh
          geometry={nodes.Cube006_1.geometry}
          material={nodes.Cube006_1.material}
        />
        <mesh
          geometry={nodes.Cube006_2.geometry}
          material={nodes.Cube006_2.material}
        />
        <mesh
          geometry={nodes.Cube006_3.geometry}
          material={nodes.Cube006_3.material}
        />
      </group>
      <group
        position={[484.31, 44.68, -169.4]}
        rotation={[0, 1.43, -1.76]}
        scale={[7.1, 5.4, 7.46]}
      >
        <mesh
          geometry={nodes.Plane022.geometry}
          material={nodes.Plane022.material}
        />
        <mesh
          geometry={nodes.Plane022_1.geometry}
          material={nodes.Plane022_1.material}
        />
      </group>
      <group
        position={[486.41, 23.97, -188.07]}
        rotation={[0, 1.43, 0.07]}
        scale={[13.5, 12.17, 20.88]}
      >
        <mesh
          geometry={nodes.Cube007_1.geometry}
          material={nodes.Cube007_1.material}
        />
        <mesh
          geometry={nodes.Cube007_2.geometry}
          material={nodes.Cube007_2.material}
        />
        <mesh
          geometry={nodes.Cube007_3.geometry}
          material={nodes.Cube007_3.material}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={nodes.Cylinder009.material}
        position={[15.57, 24.75, -139.92]}
        scale={[1.02, 13.79, 1.12]}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={nodes.Cylinder010.material}
        position={[-69.73, 24.2, -205.07]}
        scale={[1.02, 13.67, 1.12]}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={nodes.Cylinder011.material}
        position={[-27.11, 24.2, -122.64]}
        scale={[1.02, 13.67, 1.12]}
      />
      <mesh
        geometry={nodes.cube002.geometry}
        material={nodes.cube002.material}
        position={[128.28, 35.9, -80.58]}
        rotation={[1.55, 0, 0]}
        scale={[18.96, 0.42, 1.33]}
      />
      <mesh
        geometry={nodes.cube003.geometry}
        material={nodes.cube003.material}
        position={[95.35, 35.9, -80.58]}
        rotation={[1.55, 0, 0]}
        scale={[18.96, 0.42, 1.33]}
      />
      <mesh
        geometry={nodes.cube004.geometry}
        material={nodes.cube004.material}
        position={[31.85, 35.9, -80.58]}
        rotation={[1.55, 0, 0]}
        scale={[31.96, 0.42, 1.33]}
      />
      <mesh
        geometry={nodes.cube005.geometry}
        material={nodes.cube005.material}
        position={[-9.87, 35.9, -80.58]}
        rotation={[1.55, 0, 0]}
        scale={[27.57, 0.42, 1.33]}
      />
      <mesh
        geometry={nodes.cube006.geometry}
        material={nodes.cube006.material}
        position={[47.1, 35.9, -116.28]}
        rotation={[1.57, -0.02, 1.6]}
        scale={[27.57, 0.42, 1.33]}
      />
      <mesh
        geometry={nodes.cube007.geometry}
        material={nodes.cube007.material}
        position={[48.58, 35.9, -161.62]}
        rotation={[1.57, -0.02, 1.6]}
        scale={[27.57, 0.42, 1.33]}
      />
    </group>
  );
}

useGLTF.preload('/FinalInterior.glb');
